version: 0.0
Resources:
  - MyStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplatePath: template.yaml
        StackName: MyInfraStack
        Capabilities: CAPABILITY_NAMED_IAM
